aurora_config:
    generic:
        data_source: ecmwf
        data_path: /glade/derecho/scratch/turuncu/data/split_files_updated
        new_surf_vars: # mean and std values calculated from ERA5 2012-2017 data
            10w: # 10 meter wind speed, m/s
                name: w10
                mean: 6.340356e00
                std: 3.746796e00
                weight: 0.66
            2q: # 2 meter specific humidity, kg/kg
                name: q2
                mean: 0.007404
                std: 0.006230
                weight: 0.8
            2rh: # 2 meter relative humidity, fraction
                name: rh2
                mean: 0.748476
                std: 0.158421
                weight: 1.5
            2dt: # 2 meter dew point temperature, K
                name: d2m
                mean: 274.268463
                std: 20.642194
                weight: 2.0
            sst: # sea surface temperature, K
                name: sst
                mean: 287.033050
                std: 11.718787
                weight: 3.0
            swnet: # surface net shortwave radiation, W/m2
                name: ssr
                mean: 129.625259
                std: 220.336746
                weight: 1.5
            lwnet: # surface net longwave radiation, W/m2
                name: str
                mean: -52.919940
                std: 32.827163
                weight: 1.5
            swdn: # surface downwelling shortwave radiation, W/m2
                name: ssrd
                mean: 164.015975
                std: 248.105117
                weight: 2.5
            lwdn: # surface downwelling longwave radiation, W/m2
                name: strd
                mean: 303.236175
                std: 94.240333
                weight: 2.5
            tcc: # total cloud cover, fraction
                name: tcc
                mean: 0.675755
                std: 0.364521
                weight: 2.0
            tp: # total precipitation, m/s
                name: tp
                mean: 2.825574796361252e-08
                std: 1.1377525765965402e-07
                weight: 2.5
    prediction:
        steps: 2 # lead time for forecast in steps of 6 hours
        checkpoint_file: /glade/derecho/scratch/turuncu/data/aurora_runs/run_2012-2017_all_vars_tp/aurora-0.25-pretrained-new.ckpt
        batch_size: 1
        num_workers: 0 # >0 such as 4 is giving error since we are running GeoGate on a single PET
        distributed_sampler: false
